steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ng-17-tutorial:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ng-17-tutorial:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ng-17-tutorial'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ng-17-tutorial:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--min-instances=0'
      - '--max-instances=1'
      - '--port'
      - '4200'
images:
  - 'gcr.io/$PROJECT_ID/ng-17-tutorial:$COMMIT_SHA'
